
apiVersion: v1
kind: Pod
metadata:
  labels:
<% try { %>
<% build_label=(build_label) %>
<% } catch(Exception e) { %>
<% build_label='default' %>
<% } %>
    team: ${build_label}
    buildnode: 'true'
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ${build_label}
        topologyKey: kubernetes.io/hostname
  serviceAccountName: jenkins
  containers:
    - name: python
<% try { %>
<% python_image_repository=(python_image_repository) %>
<% } catch(Exception e) { %>
<% python_image_repository='python' %>
<% } %>
<% try { %>
<% python_version=(python_version) %>
<% } catch(Exception e) { %>
<% python_version='3.7' %>
<% } %>
      image: ${python_image_repository}:${python_version}
      imagePullPolicy: IfNotPresent
      command:
        - cat
      tty: true
<% try { %>
<% items=(image_dependencies) %>
<% } catch(Exception e) { %>
<% items=[] } %>
<% for (item in items) { %>
<%= item %>
<% } %>
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: dockersock
<% try { %>
<% nodeSelectorName=(nodeSelectorName) %>
  nodeSelector:
    kops.k8s.io/instancegroup: ${nodeSelectorName}
  tolerations:
    - key: 'dedicated'
      operator: Equal
      value: ${nodeSelectorName}
<% } catch(Exception e) { %>
<% } %>