@Library('ni-utils') _

//service name is extrapolated from repository name check
// def svcName = env.JOB_BASE_NAME
def svcName = (scm.getUserRemoteConfigs()[0].getUrl().tokenize('/')[3].split("\\.")[0]).toLowerCase()

// Define pod
def pod = libraryResource 'org/foo/infraTemplate.yaml'
def amazon = libraryResource 'org/foo/dependencies/amazon.yaml'
def docker = libraryResource 'org/foo/dependencies/docker.yaml'
def java = libraryResource 'org/foo/dependencies/java.yaml'
def template_vars = [
    'build_label': svcName,
    'python_version' : '3.7.13-slim',
    'image_dependencies' : [amazon, docker, java]
]
pod = renderTemplate(pod, template_vars)
print pod

// Define sharedLibrary
def sharedLibrary = new org.foo.pipelines.machineLearning() 

// Set slack channel
def slackChannel = "k8s-jenkins"

// Args for pipeline
def initiateData = [project: "ML"]
def compileData = [run: true]
def testData = [run: true]
def artifactData = [run: true, uploadTo: ["PyPi","dockerhub"]]
def intTestData = [run: false]
def deploymentData = [run: true, environments: ["staging"]]
def buildCommands = [
    initiateData: initiateData,
    compileData: compileData,
    testData: testData,
    artifactData: artifactData,
    intTestData: intTestData,
    deploymentData: deploymentData
]

timestamps {
    commonPipeline(sharedLibrary, svcName, buildCommands, pod, slackChannel)
}
